ClonedFrom: ''
PrefabName: ML_JellyFish0
Name: $enemy_ml_jellyfish0
Group: ''
Faction: Boss
Boss: false
DoNotHideBossHUD: false
BossEvent: ''
DefeatSetGlobalKey: ''
AISkipTarget: false
CrouchSpeed: 0
WalkSpeed: 3
Speed: 0.05
TurnSpeed: 300
RunSpeed: 0.05
RunTurnSpeed: 300
FlySlowSpeed: 1
FlyFastSpeed: 1
FlyTurnSpeed: 80
Acceleration: 0.05
JumpForce: 0
JumpForceForward: 0
JumpForceTiredFactor: 0
AirControl: 0.1
CanSwim: false
SwimDepth: 3
SwimSpeed: 0
SwimTurnSpeed: 30
SwimAcceleration: 0.05
GroundTilt: FullRaycast
GroundTiltSpeed: 50
Flying: false
JumpStaminaUsage: 0
DisableWhileSleeping: false
TolerateWater: true
TolerateFire: false
TolerateSmoke: true
TolerateTar: false
Health: 50
BluntResistance: Resistant
SlashResistance: Resistant
PierceResistance: Resistant
ChopResistance: Ignore
PickaxeResistance: Ignore
FireResistance: Immune
FrostResistance: Resistant
LightningResistance: Immune
PoisonResistance: Ignore
SpiritResistance: Immune
StaggerWhenBlocked: false
StaggerDamageFactor: 0
