- PrefabName: fx_swing_camshake
  Enabled: true
  Variant: -1
  Attach: true
  Follow: false
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: ''
