OriginalPrefab: ''
Name: attack_knife_slash
AnimationState: Unarmed
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 18
Pierce: 18
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 10
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Horizontal
AttackAnimation: knife_stab0
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 1.7
AttackHeight: 0.8
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 40
AttackRayWidth: 0.2
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 1
AttackMaxAngle: 25
Projectile: ''
MaterialOverride: ''
