ClonedFrom: LizardFish_RS
PrefabName: Jaegerjedd
Name: $enemy_jaegerjedd
Group: ''
Faction: MountainMonsters
Boss: false
DoNotHideBossHUD: false
BossEvent: ''
DefeatSetGlobalKey: ''
AISkipTarget: false
CrouchSpeed: 2
WalkSpeed: 5
Speed: 2
TurnSpeed: 200
RunSpeed: 6
RunTurnSpeed: 200
FlySlowSpeed: 5
FlyFastSpeed: 12
FlyTurnSpeed: 12
Acceleration: 0.5
JumpForce: 10
JumpForceForward: 0
JumpForceTiredFactor: 0.7
AirControl: 0.1
CanSwim: false
SwimDepth: 1.6
SwimSpeed: 0
SwimTurnSpeed: 100
SwimAcceleration: 0.05
GroundTilt: None
GroundTiltSpeed: 50
Flying: false
JumpStaminaUsage: 10
DisableWhileSleeping: false
TolerateWater: true
TolerateFire: false
TolerateSmoke: false
TolerateTar: false
Health: 140
BluntResistance: Normal
SlashResistance: Normal
PierceResistance: Resistant
ChopResistance: Ignore
PickaxeResistance: Ignore
FireResistance: Resistant
FrostResistance: Immune
LightningResistance: Weak
PoisonResistance: Resistant
SpiritResistance: Immune
StaggerWhenBlocked: true
StaggerDamageFactor: 0.3
