Name: Rat_attack_frost
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 25
Pierce: 15
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 15
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 15
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Projectile
AttackAnimation: attack_flames
HitTerrain: true
HitFriendly: false
DamageMultiplier: 0.35
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ik_hand_r
AttackRange: 5
AttackHeight: 1.6
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 35
AttackRayWidth: 1
MaxYAngle: 0
LowerDamagePerHit: false
HitThroughWalls: true
AttackRangeMinimum: 2
AttackInterval: 9
AttackMaxAngle: 25
Projectile: Wendigo_attack_flames_aoe
MaterialOverride: ''
