- PrefabName: vfx_wyvern_flamethrower
  Enabled: true
  Variant: 0
  Attach: false
  Follow: true
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: Jaw
