ShaderType: Snow Coverage Standard
Name: Jeddyavul_0
_Color:
  r: 0
  g: 0
  b: 0
  a: 0
_MainTex: Lizard_Albedo
_EmissionColor:
  r: 0
  g: 0
  b: 0
  a: 0
Transparent: false
_Hue: 0
_Value: 0
_Saturation: 0
