- PrefabName: vfx_skeleton_awaken
  Enabled: true
  Variant: -1
  Attach: false
  Follow: false
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: ''
