- Scale: 1
  Hue: 0
  Saturation: 0
  Value: 0
  SetEmissiveColor: false
  EmissiveColor:
    r: 0
    g: 0
    b: 0
    a: 0
  EnableObject: ''
- Scale: 1
  Hue: 0
  Saturation: 0
  Value: 0
  SetEmissiveColor: false
  EmissiveColor:
    r: 0
    g: 0
    b: 0
    a: 0
  EnableObject: ''
