ShaderType: Standard
Name: Lillfuling_0
_Color:
  r: 0.4811321
  g: 0.4811321
  b: 0.4811321
  a: 1
_MainTex: Goblin Base Albedo1
_EmissionColor:
  r: 1
  g: 0.8630775
  b: 0
  a: 1
Transparent: false
_Hue: 0
_Value: 0
_Saturation: 0
