OriginalPrefab: ''
Name: attack_mace_secondary_T3
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 45
Slash: 0
Pierce: 0
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 40
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 80
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Horizontal
AttackAnimation: mace_secondary0
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 2.2
AttackHeight: 0.8
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 90
AttackRayWidth: 0.3
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 5
AttackMaxAngle: 25
Projectile: ''
MaterialOverride: ''
