OriginalPrefab: ''
Name: CatFish_throw
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 0
Pierce: 100
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 10
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 30
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Horizontal
AttackAnimation: throw
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 1.8
AttackHeight: 1
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 90
AttackRayWidth: 0.5
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 1
AttackInterval: 8
AttackMaxAngle: 5
Projectile: ''
MaterialOverride: ''
