OriginalPrefab: ''
Name: attack_mace_right180
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 35
Pierce: 25
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 5
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 10
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Horizontal
AttackAnimation: mace_attack1
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 2
AttackHeight: 0.8
AttackOffset: 0.1
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 180
AttackRayWidth: 0.3
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 1
AttackMaxAngle: 360
Projectile: ''
MaterialOverride: ''
