- name: Basement
  alwaysDark: true
  windMax: 0
  ambientVol: 0
  ambientList: Basement
  musicMorning: '-'
  musicEvening: '-'
  musicDay: forestcrypt
  musicNight: forestcrypt
  ambColorDay:
    r: 0.3137255
    g: 0.3137255
    b: 0.3137255
    a: 1
  ambColorNight:
    r: 0.3137255
    g: 0.3137255
    b: 0.3137255
    a: 1
  sunColorMorning:
    r: 0.9411765
    g: 0.881995
    b: 0.7266436
    a: 1
  sunColorDay:
    r: 0.9491875
    g: 0.9491875
    b: 0.9491875
    a: 1
  sunColorEvening:
    r: 1
    g: 0.7426471
    b: 0.7426471
    a: 1
  sunColorNight:
    r: 0.4200909
    g: 0.4405027
    b: 0.5441177
    a: 1
  fogDensityMorning: 0
  fogDensityDay: 0
  fogDensityEvening: 0
  fogDensityNight: 0
  lightIntensityDay: 0
