- prefab: arl_foresthold
  enabled: true
  biome: BlackForest
  biomeArea: edge
  quantity: 15
  minDistance: 0.3
  maxDistance: 0.55
  minAltitude: 20
  maxAltitude: 100
  group: arl_foresthold
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 14
  clearArea: true
  randomDamage: true
- prefab: arl_foresthold_deserted
  enabled: true
  biome: BlackForest
  quantity: 10
  minDistance: 0.25
  maxDistance: 0.45
  minAltitude: 20
  maxAltitude: 100
  group: arl_foresthold
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 14
  clearArea: true
  randomDamage: true
- prefab: arl_foresthold_remnant
  enabled: true
  biome: Meadows
  quantity: 10
  minDistance: 0.2
  maxDistance: 0.4
  minAltitude: 20
  maxAltitude: 100
  group: arl_foresthold
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 14
  randomDamage: true
- prefab: arl_foresthold_ruins
  enabled: true
  biome: Mountain
  quantity: 10
  minDistance: 0.3
  maxDistance: 0.6
  minAltitude: 80
  maxAltitude: 300
  group: arl_foresthold
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 4
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 14
  randomDamage: true
- prefab: arl_instairtower
  enabled: true
  biome: Plains
  biomeArea: edge
  quantity: 10
  minDistance: 0.35
  maxDistance: 0.5
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  clearArea: true
  randomDamage: true
- prefab: arl_instairtower_damaged
  enabled: true
  biome: Plains
  biomeArea: edge
  quantity: 15
  minDistance: 0.4
  maxDistance: 0.6
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  randomDamage: true
- prefab: arl_instairtower_rebuilt
  enabled: true
  biome: Plains
  quantity: 10
  minDistance: 0.35
  maxDistance: 0.5
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  clearArea: true
  randomDamage: true
- prefab: arl_instairtower_remnant
  enabled: true
  biome: Meadows
  quantity: 15
  minDistance: 0.2
  maxDistance: 0.75
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  randomDamage: true
- prefab: arl_instairtower_reruin
  enabled: true
  biome: Plains
  quantity: 15
  minDistance: 0.4
  maxDistance: 0.6
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  randomDamage: true
- prefab: arl_instairtower_ruin
  enabled: true
  biome: BlackForest
  quantity: 15
  minDistance: 0.25
  maxDistance: 0.5
  minAltitude: 15
  maxAltitude: 100
  group: arl_instairtower
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  exteriorRadius: 10
  randomDamage: true
- prefab: arl_jarlsmanshouse
  enabled: true
  biome: Meadows
  quantity: 8
  minDistance: 0.2
  maxDistance: 0.5
  minAltitude: 20
  maxAltitude: 60
  group: arl_jarlsmanshouse
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMin: 1
  forestTresholdMax: 5
  exteriorRadius: 12
  clearArea: true
  randomDamage: true
- prefab: arl_jarlsmanshouse_remnant
  enabled: true
  biome: BlackForest
  quantity: 8
  minDistance: 0.2
  maxDistance: 0.7
  minAltitude: 20
  maxAltitude: 60
  group: arl_jarlsmanshouse
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMin: 1
  forestTresholdMax: 5
  exteriorRadius: 12
  randomDamage: true
- prefab: arl_jarlsmanshouse_ruin
  enabled: true
  biome: Meadows
  quantity: 14
  minDistance: 0.2
  maxDistance: 0.7
  minAltitude: 20
  maxAltitude: 60
  group: arl_jarlsmanshouse
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMin: 1
  forestTresholdMax: 5
  exteriorRadius: 12
  clearArea: true
  randomDamage: true
- prefab: arl_outpostcabin
  enabled: true
  biome: Mountain
  quantity: 10
  minDistance: 0.1
  maxDistance: 0.45
  minAltitude: 90
  maxAltitude: 200
  group: arl_outpostcabin
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 5
  exteriorRadius: 8
  clearArea: true
  randomDamage: true
- prefab: arl_outpostcabin_ruin
  enabled: true
  biome: Mountain
  biomeArea: edge
  quantity: 10
  minDistance: 0.1
  maxDistance: 0.45
  minAltitude: 50
  maxAltitude: 100
  group: arl_outpostcabin
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 5
  exteriorRadius: 8
  randomDamage: true
- prefab: arl_outposttower
  enabled: true
  biome: BlackForest
  quantity: 15
  minDistance: 0.2
  maxDistance: 0.4
  minAltitude: 30
  maxAltitude: 100
  group: arl_outposttower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  clearArea: true
  randomDamage: true
- prefab: arl_outposttower_burnt
  enabled: true
  biome: Plains
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.55
  minAltitude: 30
  maxAltitude: 100
  group: arl_outposttower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  randomDamage: true
- prefab: arl_outposttower_ruin
  enabled: true
  biome: Plains
  biomeArea: edge
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.55
  minAltitude: 30
  maxAltitude: 100
  group: arl_outposttower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  randomDamage: true
- prefab: arl_outposttower_remnant
  enabled: true
  biome: Plains
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.55
  minAltitude: 30
  maxAltitude: 100
  group: arl_outposttower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  randomDamage: true
- prefab: arl_pillartower
  enabled: true
  biome: Plains
  biomeArea: edge
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.55
  minAltitude: 20
  maxAltitude: 100
  group: arl_pillartower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 11
  clearArea: true
  randomDamage: true
- prefab: arl_pillartower_remnant
  enabled: true
  biome: Plains
  quantity: 15
  minDistance: 0.05
  maxDistance: 0.55
  minAltitude: 20
  maxAltitude: 100
  group: arl_pillartower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 11
  randomDamage: true
- prefab: arl_pillartower_ruin
  enabled: true
  biome: Swamp
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.75
  minAltitude: 2
  maxAltitude: 100
  group: arl_pillartower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 11
  randomDamage: true
- prefab: arl_smallonghouse
  enabled: true
  biome: Meadows
  quantity: 15
  minDistance: 0.04
  maxDistance: 0.25
  minAltitude: 5
  maxAltitude: 100
  group: arl_smallonghouse
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  clearArea: true
  randomDamage: true
- prefab: arl_swamptower
  enabled: true
  biome: Swamp
  quantity: 10
  maxDistance: 0.75
  minAltitude: 2
  maxAltitude: 100
  group: arl_swamptower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  clearArea: true
  randomDamage: true
- prefab: arl_swamptower_remnant
  enabled: true
  biome: Swamp
  quantity: 15
  maxDistance: 0.75
  minAltitude: 2
  maxAltitude: 100
  group: arl_swamptower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  randomDamage: true
- prefab: arl_swamptower_ruin
  enabled: true
  biome: Swamp
  quantity: 15
  maxDistance: 0.75
  minAltitude: 2
  maxAltitude: 100
  group: arl_swamptower
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  randomDamage: true
- prefab: arl_traphouseplain
  enabled: true
  biome: Plains
  quantity: 8
  maxDistance: 0.75
  minAltitude: 15
  maxAltitude: 100
  group: arl_traphouseplain
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 17
  clearArea: true
  randomDamage: true
- prefab: arl_traphouseplain_remnant
  enabled: true
  biome: Meadows
  quantity: 8
  minDistance: 0.2
  maxDistance: 0.75
  minAltitude: 15
  maxAltitude: 100
  group: arl_traphouseplain
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 16
  randomDamage: true
- prefab: arl_traphouseplain_ruin
  enabled: true
  biome: Plains
  quantity: 8
  maxDistance: 0.75
  minAltitude: 15
  maxAltitude: 100
  group: arl_traphouseplain
  minDistanceFromSimilar: 400
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 16
  randomDamage: true
- prefab: arl_twotwohouse
  enabled: true
  biome: Mountain
  biomeArea: edge
  quantity: 10
  minDistance: 0.1
  maxDistance: 0.35
  minAltitude: 50
  maxAltitude: 100
  group: arl_twotwohouse
  minDistanceFromSimilar: 200
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  exteriorRadius: 12
  clearArea: true
  randomDamage: true
- prefab: arl_twotwohouse_remnant
  enabled: true
  biome: Meadows
  quantity: 20
  minDistance: 0.1
  maxDistance: 0.35
  minAltitude: 15
  maxAltitude: 100
  group: arl_twotwohouse
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 4
  inForest: true
  forestTresholdMax: 3
  exteriorRadius: 12
  randomDamage: true
- prefab: arl_twotwohouse_ruin
  enabled: true
  biome: Meadows
  quantity: 20
  minDistance: 0.1
  maxDistance: 0.35
  minAltitude: 20
  maxAltitude: 100
  group: arl_twotwohouse_ruins
  minDistanceFromSimilar: 300
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  randomDamage: true
- prefab: arl_twotwohouse_stormed
  enabled: true
  biome: Mountain
  biomeArea: edge
  quantity: 10
  minDistance: 0.1
  maxDistance: 0.4
  minAltitude: 20
  maxAltitude: 100
  group: arl_twotwohouse
  minDistanceFromSimilar: 200
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2
  exteriorRadius: 12
  clearArea: true
  randomDamage: true
