Name: DwarfGoblinLoot_Run
AnimationState: Unarmed
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 0
Pierce: 0
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 0
Dodgeable: false
Blockable: false
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: None
AttackAnimation: taunt5
HitTerrain: false
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 2
AttackHeight: 0.7
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 90
AttackRayWidth: 0.3
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 15
AttackMaxAngle: 20
Projectile: ''
MaterialOverride: ''
