- PrefabName: Coins
  AmountMin: 5
  AmountMax: 8
  Chance: 1
  OnePerPlayer: false
  LevelMultiplier: true
  DoNotScale: false
- PrefabName: Amber
  AmountMin: 2
  AmountMax: 4
  Chance: 1
  OnePerPlayer: false
  LevelMultiplier: true
  DoNotScale: false
- PrefabName: Ruby
  AmountMin: 1
  AmountMax: 3
  Chance: 1
  OnePerPlayer: false
  LevelMultiplier: true
  DoNotScale: false
