# Weapon

# All power values can take a value range:
# power: [5-10, 10-15, 15-20]
# means a perfect gem rolls its power randomly between 15 and 20.

fire starter:
  slot: [weapon, elementalmagic]
  gem: red
  power: [5, 10, 16]
  # Optional Configs:
  # - chance (default: 20)

ice heart:
  slot: [weapon, elementalmagic]
  gem: blue
  power: [5, 10, 16]
  # Optional Configs:
  # - chance (default: 20)

snake bite:
  slot: [weapon, elementalmagic]
  gem: green
  power: [5, 10, 16]
  # Optional Configs:
  # - chance (default: 20)

shadow hit:
  slot: weapon
  gem: black
  power: [2, 3, 5]
  # Optional Configs:
  # - range (default: 5)
  # - amount (default: 1)

vampire:
  slot: [weapon, elementalmagic]
  gem: yellow
  power: [5, 8, 12]
  # Optional Configs:
  # - max heal (default: 6)

berserk:
  slot: [weapon, magic]
  gem: purple
  power: [1, 2, 4]

# Specific Weapons

magnetic:
  slot: spear
  gem: black
  power: [20, 30, 45]

opportunity:
  slot: axe
  gem: red
  power: [5, 7, 10]

perforation:
  slot: knife
  gem: orange
  power: [2, 4, 7]

thunderclap:
  slot: polearm
  gem: orange
  power: [3, 5, 8]

# Magic Weapons

magical bargain:
  slot: magic
  gem: orange
  power: [3, 5, 8]

precious blood:
  slot: bloodmagic
  gem: blue
  power: [3, 5, 8]

# Chest

defender:
  slot: chest
  gem: red
  power: [1, 2, 4]

vitality:
  slot: chest
  gem: blue
  power: [3, 5, 8]

regeneration:
  slot: chest
  gem: green
  power: [1, 2, 4]

mirror:
  slot: chest
  gem: black
  power: [2, 4, 7]
  # Optional Configs:
  # - damage reflected (default: 100)

fade:
  slot: chest
  gem: orange
  power: [1, 2, 4]
  # Optional Configs:
  # - damage threshold (default: 30)

# Legs

sprinter:
  slot: legs
  gem: red
  power: [2, 4, 6]

ninja:
  slot: legs
  gem: black
  power: [10, 14, 20]

nimble:
  slot: legs
  gem: blue
  power: [10, 20, 30]

marathon:
  slot: legs
  gem: yellow
  power: [6, 9, 12]

mountain goat:
  slot: legs
  gem: purple
  power: [10, 16, 25]

lifeguard:
  slot: legs
  gem: orange
  power: [20, 25, 30]

momentum:
  slot: legs
  gem: green
  power: [5, 10, 15]

# Utility

power recovery:
  slot: utility
  gem: green
  power: [10, 12, 15]

comfortable:
  slot: utility
  gem: yellow
  power: [2, 4, 7]

hercules:
  slot: utility
  gem: purple
  power: [8, 14, 22]

glowing spirit:
  slot: utility
  gem: blue
  power: [4, 6, 8]

dungeon guide:
  slot: utility
  gem: black
  power: [2, 4, 6]

daring:
  slot: utility
  gem: orange
  power: [10, 20, 30]

wisplight:
  slot: utility
  gem: wisplight
  power: 10

wishbone:
  slot: utility
  gem: wishbone
  power: 10

# Head

explorer:
  slot: head
  gem: green
  power: [10, 15, 25]

student:
  slot: head
  gem: red
  power: [2, 3, 6]

resilience:
  slot: head
  gem: yellow
  power: [5, 7, 10]

gourmet:
  slot: head
  gem: purple
  power: [10, 14, 20]

merciful death:
  slot: head
  gem: blue
  power: [10, 15, 20]

eitr surge:
  slot: head
  gem: orange
  power: [3, 5, 8]

# Bow

endless arrows:
  slot: bow
  gem: red
  power: [4, 6, 10]

master archer:
  slot: bow
  gem: purple
  power: [4, 6, 10]

stealth archer: unset
#  slot: bow
#  gem: black
#  power: [20, 35, 50]

quick draw:
  slot: bow
  gem: black
  power: [3, 5, 8]

# Crossbow

endless bolts:
  slot: crossbow
  gem: red
  power: [4, 6, 10]

master arbalist:
  slot: crossbow
  gem: purple
  power: [4, 6, 10]

quick load:
  slot: crossbow
  gem: black
  power: [3, 5, 8]

# Bow and Crossbow

echo:
  slot: [bow, crossbow]
  gem: yellow
  power: [2, 3, 5]
  # Optional Configs:
  # - bonus projectiles (default: 1)

necromancer:
  slot: [bow, crossbow]
  gem: green
  power: [3, 5, 8]
  # Optional Configs:
  # - duration (default: 10)

ricochet:
  slot: [bow, crossbow]
  gem: orange
  power: [3, 5, 8]
  # Optional Configs:
  # - range (default: 15)

elemental chaos:
  slot: [bow, crossbow]
  gem: blue
  power: [10, 15, 20]
  # Optional Configs:
  # - chance (default: 20)

# Cloak

glider:
  slot: cloak
  gem: green
  power: [3, 5, 7]
  # Optional Configs:
  # - required height (default: 3.5)

inconspicuous:
  slot: cloak
  gem: black
  power: [10, 15, 20]

turtle shell:
  slot: cloak
  gem: yellow
  power: [8, 10, 14]

wind walk:
  slot: cloak
  gem: purple
  power: [5, 10, 20]

air dried:
  slot: cloak
  gem: blue
  power: [10, 20, 35]

# Shield

unfazed:
  slot: shield
  gem: blue
  power: [8, 16, 25]

parry master:
  slot: shield
  gem: purple
  power: [50, 80, 100]

avoidance:
  slot: shield
  gem: yellow
  power: [1, 2, 4]
  # Optional Configs:
  # - damage reduction (default 100)

tank:
  slot: shield
  gem: black
  power: [3, 6, 10]

pain tolerance:
  slot: shield
  gem: red
  power: [1, 2, 4]

fast reaction:
  slot: shield
  gem: orange
  power:
    parry frame decrease: [50, 85, 120]
    parry power increase: [10, 20, 30]

vampiric parry:
  slot: shield
  gem: green
  power: [1, 2, 4]

# Tool

unbreakable:
  slot: tool
  gem: purple
  power: [40, 50, 60]

energetic:
  slot: tool
  gem: yellow
  power: [15, 25, 30]

frenzy:
  slot: tool
  gem: black
  power: [5, 10, 15]

# Boss

lightning speed:
  slot: all
  gem: eikthyr
  power:
    movement speed: 60
    min cooldown: 90
    max cooldown: 120
    duration: 8
    attack speed: 100
    stamina: 50
    damage reduction: 40
  unique: all

rooted revenge:
  slot: all
  gem: elder
  power:
    bonus damage: 25
    min cooldown: 120
    max cooldown: 180
    duration: 9
    range: 12
  unique: all

poisonous drain:
  slot: all
  gem: bonemass
  power:
    healing increase: 100
    min cooldown: 180
    max cooldown: 210
    duration: 8
    poison damage: 40
    life steal: 20
  unique: all

icy protection:
  slot: all
  gem: moder
  power:
    damage reduction: 90
    min cooldown: 180
    max cooldown: 210
    duration: 8
    drakes: 3
  unique: all

fiery doom:
  slot: all
  gem: yagluth
  power:
    stagger chance: 30
    min cooldown: 180
    max cooldown: 240
    duration: 8
    fire damage: 200
  unique: all

apotheosis:
  slot: all
  gem: queen
  power:
    eitr reduction: 100
    min cooldown: 150
    max cooldown: 210
    duration: 8
    magic damage increase: 15
    attack speed: 20
  unique: all

lizard friendship:
  slot: all
  gem: fader
  power:
    movement damage: 100
    min cooldown: 420
    max cooldown: 600
    duration: 30
    speed increase: 15
    health increase: 200
    spawn range: 20
  unique: all

# Gem Spawn

gems:
  meadows:
    green: 0.41
    black: 0.015
    purple: 0.015
    blue: 0.015
    yellow: 0.015
    red: 0.015
    orange: 0.015
  black forest:
    green: 0.015
    black: 0.41
    purple: 0.015
    blue: 0.015
    yellow: 0.015
    red: 0.015
    orange: 0.015
  swamp:
    green: 0.015
    black: 0.015
    purple: 0.41
    blue: 0.015
    yellow: 0.015
    red: 0.015
    orange: 0.015
  mountain:
    green: 0.015
    black: 0.015
    purple: 0.015
    blue: 0.41
    yellow: 0.015
    red: 0.015
    orange: 0.015
  plains:
    green: 0.015
    black: 0.015
    purple: 0.015
    blue: 0.015
    yellow: 0.41
    red: 0.015
    orange: 0.015
  ash lands:
    green: 0.015
    black: 0.015
    purple: 0.015
    blue: 0.015
    yellow: 0.015
    red: 0.41
    orange: 0.015
  mistlands:
    green: 0.015
    black: 0.015
    purple: 0.015
    blue: 0.015
    yellow: 0.015
    red: 0.015
    orange: 0.41