leading wolf:
  slot: cloak
  gem: cyan
  power: [7, 9, 12]

shared healing:
  slot: head
  gem: cyan
  power: [8, 16, 30]

fleeting life:
  slot: weapon
  gem: cyan
  power: [6, 8, 10]

safe haven:
  slot: chest
  gem: cyan
  power: [1, 2, 4]

cowardice:
  slot: legs
  gem: cyan
  power: [3, 4, 6]
  # Optional Configs:
  # - duration (default: 20)
  # - max stacks (default: 5)

archery mentor:
  slot: bow
  gem: cyan
  power: [15, 30, 45]

arbalist mentor:
  slot: crossbow
  gem: cyan
  power: [15, 30, 45]

dedicated tank:
  slot: shield
  gem: cyan
  power: [50, 60, 70]

extensive embrace:
  item: StaffShield
  gem: cyan
  power: [2, 4, 6]

together forever:
  slot: all
  gem: group
  power:
    movement speed: 30
    min cooldown: 45
    max cooldown: 90
    duration: 8
    attack speed: 20
    damage increase: 10
    movement speed reduction: 50
    damage taken increase: 100
  unique: all

# Gem Spawn

gems:
  meadows:
    cyan: 0.03
  black forest:
    cyan: 0.04
  swamp:
    cyan: 0.05
  mountain:
    cyan: 0.06
  plains:
    cyan: 0.07
  ash lands:
    cyan: 0.05
  mistlands:
    cyan: 0.05

# Synergies

cyan is the most common color:
  conditions:
    - cyan > max other
  effect:
    never alone: 100