ShaderType: Custom/Creature
Name: MAT_SKELETON_WARRIOR_ARMOR
_Color:
  r: 1
  g: 1
  b: 1
  a: 1
_MainTex: T_SKELETON_WARRIOR_Armor_BaseColor
_EmissionColor:
  r: 0
  g: 0
  b: 0
  a: 0
Transparent: false
_Hue: 0
_Value: 0
_Saturation: 0
