Name: WereBoar_attack_IceNova
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 110
Pierce: 0
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 50
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: area
AttackAnimation: attack_nova
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 0.9
AttackHeight: 1.5
AttackOffset: 0.3
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 90
AttackRayWidth: 0.3
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 15
AttackMaxAngle: 45
Projectile: ''
MaterialOverride: ''
