OriginalPrefab: ''
Name: attack_pickaxe_slash_T1
AnimationState: TwoHandedClub
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 10
Pierce: 10
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 50
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: digg_v3
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Vertical
AttackAnimation: swing_pickaxe
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 2
AttackHeight: 1
AttackOffset: 0
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 40
AttackRayWidth: 0.2
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 0
AttackInterval: 2.5
AttackMaxAngle: 25
Projectile: ''
MaterialOverride: ''
