ShaderType: Snow Coverage Standard
Name: Hatchling_mountain_mat1
_Color:
  r: 0
  g: 0
  b: 0
  a: 0
_MainTex: Hatchling_mountain_mat1
_EmissionColor:
  r: 0
  g: 0
  b: 0
  a: 0
Transparent: false
_Hue: 0
_Value: 0
_Saturation: 0
