ClonedFrom: ''
PrefabName: PoisonSkeletonWarriorNoFx
Name: $enemy_nofxpoisonskeleton
Group: ''
Faction: Undead
Boss: false
DoNotHideBossHUD: false
BossEvent: ''
DefeatSetGlobalKey: ''
AISkipTarget: false
CrouchSpeed: 2
WalkSpeed: 0.5
Speed: 1
TurnSpeed: 300
RunSpeed: 5
RunTurnSpeed: 100
FlySlowSpeed: 5
FlyFastSpeed: 12
FlyTurnSpeed: 12
Acceleration: 0.1
JumpForce: 10
JumpForceForward: 10
JumpForceTiredFactor: 0.7
AirControl: 0.1
CanSwim: false
SwimDepth: 0.8
SwimSpeed: 0
SwimTurnSpeed: 100
SwimAcceleration: 0.05
GroundTilt: None
GroundTiltSpeed: 50
Flying: false
JumpStaminaUsage: 10
DisableWhileSleeping: false
TolerateWater: true
TolerateFire: false
TolerateSmoke: true
TolerateTar: false
Health: 40
BluntResistance: Resistant
SlashResistance: Resistant
PierceResistance: Resistant
ChopResistance: Ignore
PickaxeResistance: Ignore
FireResistance: Immune
FrostResistance: Weak
LightningResistance: Weak
PoisonResistance: Immune
SpiritResistance: Weak
StaggerWhenBlocked: true
StaggerDamageFactor: 0.5
