- PrefabName: fx_wendigo_frost_hand
  Enabled: true
  Variant: 0
  Attach: false
  Follow: true
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: Character1_RightHand
- PrefabName: fx_wendigo_frost_hand
  Enabled: true
  Variant: 0
  Attach: false
  Follow: true
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: Character1_LeftHand
