- PrefabName: sfx_ratbrute_alerted
  Enabled: true
  Variant: 0
  Attach: false
  Follow: false
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: ''
- PrefabName: sfx_fenring_alerted
  Enabled: true
  Variant: -1
  Attach: false
  Follow: false
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: 
- PrefabName: sfx_boar_alerted
  Enabled: true
  Variant: -1
  Attach: false
  Follow: false
  InheritParentRotation: false
  InheritParentScale: false
  MultiplyParentVisualScale: false
  RandomRotation: false
  Scale: false
  ChildTransform: 
