Name: WereBoar_attack_frost
AnimationState: OneHanded
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 80
Pierce: 25
Chop: 0
Pickaxe: 0
Fire: 0
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 45
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Horizontal
AttackAnimation: attack_flames
HitTerrain: true
HitFriendly: false
DamageMultiplier: 0.34
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 0.34
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 4
AttackHeight: 1.5
AttackOffset: 0.3
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 35
AttackRayWidth: 1
MaxYAngle: 30
LowerDamagePerHit: false
HitThroughWalls: true
AttackRangeMinimum: 2
AttackInterval: 10
AttackMaxAngle: 20
Projectile: ''
MaterialOverride: ''
