OriginalPrefab: ''
Name: succubus_attack_bow
AnimationState: Bow
ToolTier: 0
Damage: 0
Blunt: 0
Slash: 0
Pierce: 60
Chop: 0
Pickaxe: 0
Fire: 50
Frost: 0
Lightning: 0
Poison: 0
Spirit: 0
AttackForce: 15
Dodgeable: true
Blockable: true
SpawnOnHit: ''
SpawnOnHitTerrain: ''
AttackStatusEffect: ''
AttackStatusEffectChance: 1
AttackType: Projectile
AttackAnimation: bow_fire
HitTerrain: true
HitFriendly: false
DamageMultiplier: 1
DamageMultiplierPerMissingHP: 0
DamageMultiplierByTotalHealthMissing: 0
ForceMultiplier: 1
StaggerMultiplier: 1
RecoilPushback: 0
SelfDamage: 0
AttackOriginJoint: ''
AttackRange: 1
AttackHeight: 1.5
AttackOffset: 0.1
SpawnOnTrigger: ''
ToggleFlying: false
Attach: false
AttackAngle: 90
AttackRayWidth: 0
MaxYAngle: 0
LowerDamagePerHit: true
HitThroughWalls: false
AttackRangeMinimum: 2
AttackInterval: 1
AttackMaxAngle: 25
Projectile: npc_fire_arrow_projectile
MaterialOverride: ''
